[trampoline]
name = "{{PROJ_NAME}}"
mode = "dev"
path = "{{BASE_PROJ_PATH}}"

[[default_contracts]]
name = "pwlock"
path = "pw_anyone_can_pay"

[[default_contracts]]
name = "sudt"
path = "deps/ckb-scripts/build/simple_udt"

[[contracts]]
name = "dummy"
path = "dummy"

